
[general]
	#The material blacklist of this module.
	materialBlacklist = ["salt", "lapis_lazuli", "nether_brick", "obsidian", "brick", "wood", "neptunium", "mana_diamond", "dragonstone", "certus", "certus_quartz", "charged_certus_quartz"]

