
[MachineResourceProductionConfig]

	[MachineResourceProductionConfig.BlockBreakerConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineResourceProductionConfig.MarineFisherConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [5000FE]
		powerPerOperation = 5000
		#Max Stored Power [FE] - Default: [20000 FE]
		maxStoredPower = 20000

	[MachineResourceProductionConfig.ResourcefulFurnaceConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 40
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Essence] - Default: [8000mB]
		maxEssenceTankSize = 16000

	[MachineResourceProductionConfig.FluidPlacerConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Input] - Default: [8000mB]
		maxInputTankSize = 16000

	[MachineResourceProductionConfig.BlockPlacerConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineResourceProductionConfig.FluidCollectorConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Output] - Default: [8000mB]
		maxOutputTankSize = 16000

	[MachineResourceProductionConfig.MechanicalDirtConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Meat] - Default: [8000mB]
		maxMeatTankSize = 4000

	[MachineResourceProductionConfig.WaterCondensatorConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [100 (5s)]
		maxProgress = 100
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerOperation = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Water] - Default: [8000mB]
		maxWaterTankSize = 16000

	[MachineResourceProductionConfig.SporeRecreatorConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Water] - Default: [8000mB]
		maxWaterTankSize = 1000

	[MachineResourceProductionConfig.SludgeRefinerConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 1000
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Sludge] - Default: [8000mB]
		maxSludgeTankSize = 8000

	[MachineResourceProductionConfig.DyeMixerConfig]
		#Amount of Power Consumed per Tick - Default: [400FE]
		powerPerTick = 30
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000

	[MachineResourceProductionConfig.MaterialStoneWorkFactoryConfig]
		#Cooldown Time in Ticks [20 Ticks per Second] - Default: [60 (3s)]
		maxProgress = 60
		#Amount of Power Consumed per Tick - Default: [60FE]
		powerPerTick = 60
		#Max Stored Power [FE] - Default: [10000 FE]
		maxStoredPower = 10000
		#Max Amount of Stored Fluid [Water] - Default: [2000mB]
		maxWaterTankSize = 2000
		#Max Amount of Stored Fluid [Lava] - Default: [2000mB]
		maxLavaTankSize = 2000

