
#These settings affects both server and client, they will also be synced from server to client
[Server]
	#Whether or not to disable the RecipeBook in the CosmeticArmorInventory
	CosArmorDisableRecipeBook = false

