
[rendering]
	#Whitelist of dimension ID's that will have special astral sorcery sky rendering
	skyRenderDimensions = [0]
	#Enables/Disables all patreon effects.
	patreonEffects = true
	#Sets the amount of particles/effects: MINIMAL, LOWERED, ALL
	#Allowed Values: NONE, MINIMAL, LOWERED, ALL
	particleAmount = "ALL"
	#IF a dimensionId is listed in 'skySupportedDimensions' you can add it here to keep its sky render, but AS will try to render only constellations on top of its existing sky render.
	weakSkyRenders = []
	#Defines how close to the position of a particle/floating texture you have to be in order for it to render.
	#Range: 1.0 ~ 512.0
	maxEffectRenderDistance = 64.0

