
["YUNG's Better Mineshafts"]
	"Enable Ice Variant" = true
	"Enable Jungle Variant" = true
	"Enable Mushroom Variant" = true
	"Enable Desert Variant" = true
	"Enable Red Desert Variant" = true
	"Enable Snow Variant" = true
	"Mineshaft Spawn Rate" = 0.003
	"Enable Mesa Variant" = true
	"Enable Savanna Variant" = true
	# The lowest the floor of the shaft can be.
	# Default: 13
	"Minimum y-coordinate" = 13
	# The highest the floor of the shaft can be.
	# Be careful, setting this too high can make mineshafts poke through ocean floors.
	# Default: 37
	"Maximum y-coordinate" = 37

