
#Tool settings
[tools]
	#Determines whether you need a hammer to remove blocks from a frame, when set to false, you can remove blocks from a frame by sneaking and right-clicking the block (default: true)
	hammer_needed = true

