
["Miscellaneous Features"]
	#Configures if right-click harvesting of crops should be enabled. Which crops are affected by right-clicking can be configured in the "Right-click Harvesting Settings" section.
	#DISABLED -> disables right-click harvesting feature for all crops completely
	#ENABLED_DROP -> loot is dropped on the ground
	#ENABLED_SMART -> loot is placed in the player's inventory
	#Allowed Values: DISABLED, ENABLED_DROP, ENABLED_SMART
	"Right-Click Harvest" = "ENABLED_DROP"
	#Configures if Double Crops (i.e. Corn, Sorghum, Kenaf) slow down living entities (Default: false)
	"Double Crops Slow Down Motion" = true

["Dimensions Settings"]
	#Enter a dimension id to whitelist feature generation
	white_dim = [0]
	#Enter a dimension id to blacklist feature generation
	black_dim = [-1, 1]

["Tweak World Generation Rates"]
	#Chance of fruit trees generating in the overworld. Higher numbers indicate a lower probability (Default: 1500)
	#Range: 1 ~ 1000000000
	"Probability of fruit trees generating" = 10000
	#Chance of opuntias generating in deserts. Higher numbers indicate a lower probability (Default: 150)
	#Range: 1 ~ 1000000000
	"Probability of opuntias generating" = 1500
	#Chance of wild crops generating in the overworld. Higher numbers indicate a lower probability (Default: 100)
	#Range: 1 ~ 1000000000
	"Probability of wild crops generating" = 3000
	#Chance of wild plants generating in the overworld. Higher numbers indicate a lower probability (Default: 800)
	#Range: 1 ~ 1000000000
	"Probability of wild plants generating" = 8000
	#Chance of berry bushes generating in the overworld. Higher numbers indicate a lower probability (Default: 300)
	#Range: 1 ~ 1000000000
	"Probability of berry bushes generating" = 2000

["Enable/Disable World Generation"]
	#Enable this feature to avoid conflicts with other mods that add grass drops (And disable grass drops).
	"Generate wild crops" = false
	#Indicates whether opuntias (cactus crops) should generate
	"Generate opuntias" = true
	#Indicates whether fruit trees should generate
	"Generate fruit trees" = true
	#Indicates whether wild plants, such as quinoa and cumin, should generate
	"Generate wild plants" = true
	#Indicates whether berry bushes should generate
	"Generate berry bushes" = true
	#Indicates whether vanilla pumpkin and melon stems should be replaced by a single block crop
	"Replace stems" = false

["Right-click Harvesting Settings"]
	#Indicates whether right-click harvesting opuntias should be enabled
	"Enable right-click harvesting for opuntias" = true
	#Indicates whether right-click harvesting double-high-crops should be enabled
	"Enable right-click harvesting for double-high-crops" = false
	#Indicates whether right-click harvesting grapes should be enabled
	"Enable right-click harvesting for grapes" = true
	#Indicates whether right-click harvesting crops should be enabled
	"Enable right-click harvesting for crops" = false
	#Indicates whether right-click harvesting berry bushes should be enabled
	"Enable right-click harvesting for berry bushes" = true
	#Indicates whether right-click harvesting tree leaves should be enabled
	"Enable right-click harvesting for tree leaves" = true
	#Indicates whether right-click harvesting wild plants should be enabled
	"Enable right-click harvesting for wild plants" = true

